<a href="https://colab.research.google.com/github/Cesar200210/Inteligencia-Artificial-/blob/main/PruebaRealizada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
import numpy as np

# Crear un vector aleatorio de tamaño 10
random_vector = np.random.rand(10)
print("Vector aleatorio original:", random_vector)

# Reemplazar el valor máximo en el vector por 0
random_vector[random_vector.argmax()] = 0
print("Vector después de reemplazar el valor máximo por 0:", random_vector)


Vector aleatorio original: [0.20210627 0.03747241 0.10875947 0.42610515 0.31875857 0.29126417
 0.02240308 0.30483747 0.94197903 0.3630224 ]
Vector después de reemplazar el valor máximo por 0: [0.20210627 0.03747241 0.10875947 0.42610515 0.31875857 0.29126417
 0.02240308 0.30483747 0.         0.3630224 ]


In [17]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# Imprimir el número 8
number_8 = arr[1, 2]
print(number_8)

8


In [19]:
# Dado de matriz
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Imprimir los números [3, 4, 5]
subset = arr[2:5]
print(subset)

[3 4 5]


In [21]:
import numpy as np

# Dado de matriz
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Imprimir los últimos 4 números
last_four_numbers = arr[-4:]
print(last_four_numbers)


[4 5 6 7]


In [23]:
import numpy as np

# Crear un array de 3x3 con todos los valores True
array_true = np.full((3, 3), True)
print(array_true)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [25]:
import numpy as np

# Dado de matriz
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Extraer todos los números impares
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]


In [27]:
import numpy as np

# Crear un vector con valores del 10 al 49
vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [29]:
def reverse_vector(vector):
    return vector[::-1]

# Ejemplo:
original_vector = [1, 2, 3, 4, 5]
reversed_vector = reverse_vector(original_vector)
print("Original:", original_vector)
print("Invertido:", reversed_vector)

Original: [1, 2, 3, 4, 5]
Invertido: [5, 4, 3, 2, 1]


In [31]:
import numpy as np

# Uuna matriz de 10x10 con valores enteros aleatorios entre 0 y 100
array = np.random.randint(0, 101, size=(10, 10))

# Encuentra valores mínimos y máximos.
min_value = np.min(array)
max_value = np.max(array)

print("Array:")
print(array)
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)

Array:
[[ 41  15   9   7  95  39  45  40  36  92]
 [ 70  99   5  52  18  42  63  33  87  96]
 [ 34   2  63  91   3  46  53  27   4  34]
 [ 97  94 100   3  99  94  99  99   5  62]
 [ 75  59  76  32  55   9  18  87   0  76]
 [ 98   4  35  78  99  41  23  29  89  88]
 [  5  39  20  83  17  85  28  59  34  42]
 [  6  23  72  70  10  28  96   1  19  40]
 [ 16  78  68  65   9  64  86  44  56  73]
 [ 21  65  15   5   6   9  50  27  77  44]]

Minimum value: 0
Maximum value: 100


In [33]:
import numpy as np

# Una matriz de 3x3x3 con valores aleatorios
array = np.random.rand(3, 3, 3)

print("Matriz 3x3x3 con valores aleatorios:")
print(array)

Matriz 3x3x3 con valores aleatorios:
[[[0.50250036 0.99759591 0.33298879]
  [0.21577088 0.90634847 0.06778967]
  [0.11487374 0.52189598 0.45181286]]

 [[0.25611784 0.23426373 0.89285471]
  [0.37634626 0.9972372  0.68514653]
  [0.10651207 0.94610602 0.76428315]]

 [[0.88458558 0.91938246 0.52112431]
  [0.9977023  0.78465012 0.86864314]
  [0.4657582  0.40967111 0.27120322]]]


In [35]:
import numpy as np

# Matriz de ejemplo
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Reemplazar números impares con -1
arr[arr % 2 != 0] = -1

print("Matriz modificada:")
print(arr)

Matriz modificada:
[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


In [37]:
import numpy as np

# Crea una matriz de tipo float
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]], dtype=float)

print("Matriz de tipo flotante:")
print(arr)

Matriz de tipo flotante:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [39]:
import numpy as np

# Ejemplo de matriz 1D
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Convertir a una matriz 2D con 2 filas
arr_2d = arr_1d.reshape(2, -1)  # -1 en remodelación infiere la dimensión restante

print("Original 1D matriz:")
print(arr_1d)
print("\nMatriz 2D convertida con 2 filas:")
print(arr_2d)

Original 1D matriz:
[1 2 3 4 5 6]

Matriz 2D convertida con 2 filas:
[[1 2 3]
 [4 5 6]]


In [41]:
import numpy as np

# Matrices de ejemplo
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

# Encuentre valores comunes entre Z1 y Z2
common_values = np.intersect1d(Z1, Z2)

print("Matriz Z1:", Z1)
print("Matriz Z2:", Z2)
print("\nValores comunes entre Z1 y Z2:", common_values)

Matriz Z1: [9 2 5 2 9 3 1 6 4 1]
Matriz Z2: [9 1 2 9 9 1 0 6 3 7]

Valores comunes entre Z1 y Z2: [1 2 3 6 9]


In [43]:
import numpy as np

# Generar matrices aleatorias A y B
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# Compruebe si las matrices A y B son iguales
are_equal = np.array_equal(A, B)

print("Matriz A:", A)
print("Matriz B:", B)

if are_equal:
    print("\nLas matrices A y B son iguales.")
else:
    print("\nLas matrices A y B no son iguales.")

Matriz A: [1 0 1 1 0]
Matriz B: [1 1 0 1 1]

Las matrices A y B no son iguales.


In [45]:
import numpy as np

# Matrices de ejemplo
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7, 8, 9],
              [10, 11, 12]])

# Apilar matrices a y b verticalmente
stacked_array = np.vstack((a, b))

print("Matriz a:")
print(a)
print("\nMatriz b:")
print(b)
print("\nMatriz apilada verticalmente:")
print(stacked_array)

Matriz a:
[[1 2 3]
 [4 5 6]]

Matriz b:
[[ 7  8  9]
 [10 11 12]]

Matriz apilada verticalmente:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [47]:
import numpy as np

# Matrices de ejemplo
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# Apilar las matrices a y b horizontalmente
stacked_array = np.hstack((a, b))

print("Matriz a:")
print(a)
print("\nMatriz b:")
print(b)
print("\nMatriz apilada horizontalmente:")
print(stacked_array)


Matriz a:
[[1 2]
 [3 4]]

Matriz b:
[[5 6]
 [7 8]]

Matriz apilada horizontalmente:
[[1 2 5 6]
 [3 4 7 8]]


In [49]:
import numpy as np

tmp = np.arange(15)

# Consigue artículos entre 5 y 10
result = tmp[(tmp > 5) & (tmp < 10)]

print("Matriz original tmp:")
print(tmp)
print("\nArtículos entre 5 y 10:")
print(result)

Matriz original tmp:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Artículos entre 5 y 10:
[6 7 8 9]


In [51]:
import numpy as np

def pair_max(x, y):
    """Obtenga el máximo de elementos de dos matrices"""
    return np.maximum(x, y)

# Ejemplo:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = pair_max(a, b)
print(result)

[6 7 9 8 9 7 5]


In [53]:
import numpy as np

arr = np.arange(9).reshape(3, 3)
print("Original matriz:")
print(arr)

# Intercambiar columnas 1 y 2
arr[:, [1, 2]] = arr[:, [2, 1]]

print("\nMatriz después de intercambiar las columnas 1 y 2:")
print(arr)

Original matriz:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Matriz después de intercambiar las columnas 1 y 2:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [54]:
import numpy as np

# Genere una matriz de 5x3 de números decimales aleatorios entre 5 y 10
arr = np.random.uniform(5, 10, size=(5, 3))

print("Matriz aleatoria de 5x3 entre 5 y 10:")
print(arr)

Matriz aleatoria de 5x3 entre 5 y 10:
[[9.25565622 5.85296811 8.88268415]
 [5.37140743 7.86202658 6.98055839]
 [9.02216898 6.76879127 5.72562713]
 [7.95308096 8.73382371 9.22937851]
 [6.31080801 8.6684226  5.78825459]]
